/* StaXX — generates tests/server/REGISTRY-BEHAVIOUR.md from the two registry
 * suites' own JSON dumps (PLAN_92b Stage 3).
 * Copyright 2026, StaXX contributors. GPL-2.0.
 *
 *   node tests/registry_note.js <quirks.json> <selfhosted.json> [--out <path>]
 *   node tests/registry_note.js --selftest
 *
 * No framework, no npm, no network — the same shape as yaml_roundtrip.js and
 * stash_guard.js: one line per case in self-test mode, and a non-zero exit
 * if anything fails.
 *
 * Why generated rather than hand-kept: the note's whole value is that it
 * cannot go stale without the suites themselves changing. Every fact in
 * section 4 is keyed off a value actually present in the dump — never typed
 * in — so a tenth registry, or a registry that changes behaviour, changes
 * the note the next time this runs, with nothing for a person to remember.
 */

'use strict';

var fs   = require('fs');
var path = require('path');

var ROOT        = path.join(__dirname, '..');
var DEFAULT_OUT = path.join(ROOT, 'tests', 'server', 'REGISTRY-BEHAVIOUR.md');

var PUBLIC_REGISTRIES = [
  'docker.io', 'ghcr.io', 'lscr.io', 'quay.io', 'public.ecr.aws',
  'mcr.microsoft.com', 'registry.k8s.io', 'codeberg.org', 'registry.gitlab.com'
];

/* ---- plain-word rendering of raw observed values ------------------------
 * Each maps a value the suites actually print to a plain sentence fragment.
 * An unrecognised value is shown verbatim rather than swallowed, so a new
 * value the suite starts printing is visible instead of silently blank. */

function wordChallenge(v) {
  return { bearer: 'bearer token', none: 'none needed', unreachable: 'unreachable',
           unsupported: 'unsupported scheme', 'parse failed': 'could not be parsed' }[v] || v;
}
function wordToken(v) {
  return { yes: 'yes', 'n/a': 'not applicable', FAILED: 'FAILED', '?': 'unknown' }[v] || v;
}
function word304(v) {
  return { yes: 'yes', 'no (200)': 'no — answers 200', 'no etag sent': 'no — no entity tag sent',
           FAILED: 'FAILED', '?': 'unknown' }[v] || v;
}
function wordRatelimit(v) {
  return { yes: 'yes', 'not sent': 'no', FAILED: 'FAILED', '?': 'unknown' }[v] || v;
}
function wordDigestMatch(v) {
  return { yes: 'yes', NO: 'NO', skip: 'skipped', unreachable: 'unreachable',
           FAILED: 'FAILED', '?': 'unknown' }[v] || v;
}
function wordDigestFrom(v) {
  return { header: "from the registry's header",
           'computed (no header)': 'computed from the bytes served', '?': 'unknown' }[v] || v;
}

/* ---- small helpers -------------------------------------------------------- */

function joinList(items) {
  if (items.length === 0) return '';
  if (items.length === 1) return items[0];
  return items.slice(0, -1).join(', ') + ' and ' + items[items.length - 1];
}

function mdEscape(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|');
}

function row(cells) {
  return '| ' + cells.map(mdEscape).join(' | ') + ' |';
}

/* ---- loading and refusing ------------------------------------------------- */

// Returns {ok:true, data} or {ok:false, error}. Never throws — every failure
// mode (missing file, bad JSON, no rows) is a refusal message, not a stack
// trace, because this runs unattended alongside a server suite.
function loadDump(filePath, label) {
  var text;
  try {
    text = fs.readFileSync(filePath, 'utf8');
  } catch (e) {
    return { ok: false, error: 'could not read the ' + label + ' dump at ' + filePath + ': ' + e.message };
  }
  var data;
  try {
    data = JSON.parse(text);
  } catch (e) {
    return { ok: false, error: 'the ' + label + ' dump at ' + filePath + ' is not valid JSON: ' + e.message };
  }
  if (!data || typeof data !== 'object' || data.rows === undefined || data.rows === null) {
    return { ok: false, error: 'the ' + label + ' dump at ' + filePath + ' has no "rows"' };
  }
  return { ok: true, data: data };
}

// A dump measured during a broken run is the stale-note problem in a new
// coat — refuse to publish a table from it rather than publish a table that
// looks authoritative and is not.
function checkClean(data, label) {
  var fails = Number(data.fails || 0);
  if (fails !== 0) {
    // The suite the dump names itself is the one that ran; the label is only a
    // fallback for a dump that forgot to say.
    return { ok: false, error: (data.suite || label) + ' reports ' + fails +
             ' failing case' + (fails === 1 ? '' : 's') + ' — refusing to write a note from a broken run' };
  }
  return { ok: true };
}

/* ---- building the note ----------------------------------------------------- */

function buildHeader(quirks, selfhosted) {
  var lines = [];
  lines.push('# What every registry turned out to do');
  lines.push('');
  lines.push('This file is generated by `tests/registry_note.js` from two suites’ own output —');
  lines.push('`registry_quirks.php` (nine public registries) and `registry_selfhosted.php` (three');
  lines.push('self-hosted ones). Hand-editing it is pointless: the next run overwrites it.');
  lines.push('');
  lines.push('- `registry_quirks.php` — run on ' + (quirks.date || '?') + ', ' +
             (quirks.passes || 0) + ' passed, ' + (quirks.fails || 0) + ' failed, ' +
             (quirks.skips || 0) + ' skipped.');
  lines.push('- `registry_selfhosted.php` — run on ' + (selfhosted.date || '?') + ', ' +
             (selfhosted.passes || 0) + ' passed, ' + (selfhosted.fails || 0) + ' failed, ' +
             (selfhosted.skips || 0) + ' skipped.');
  lines.push('');
  return lines;
}

function buildPublicTable(rows) {
  var lines = [];
  lines.push('## Public registries');
  lines.push('');
  lines.push(row(['Registry', 'Sign-in challenge', 'Token needed', 'Conditional re-ask honoured',
                  'Reports its own allowance', 'Digest matched the docker CLI', 'Digest came from']));
  lines.push(row(['---', '---', '---', '---', '---', '---', '---']));
  rows.forEach(function (r) {
    lines.push(row([
      r.registry, wordChallenge(r.challenge), wordToken(r.token), word304(r['304']),
      wordRatelimit(r.ratelimit), wordDigestMatch(r.digest_match), wordDigestFrom(r.digest_from)
    ]));
  });
  lines.push('');
  return lines;
}

function buildSelfhostedTable(rows) {
  rows = rows || {};
  var lines = [];
  lines.push('## Self-hosted registries');
  lines.push('');
  lines.push(row(['Registry', 'Challenge', 'Digest matched the CLI', 'Conditional re-ask', 'Manifest shape served']));
  lines.push(row(['---', '---', '---', '---', '---']));
  ['open', 'zot'].forEach(function (key) {
    var r = rows[key];
    if (!r) return;
    lines.push(row([r.registry || key, wordChallenge(r.challenge), wordDigestMatch(r.digest_match),
                     word304(r['304']), r.shape || 'not measured in this run']));
  });
  lines.push('');
  ['open', 'zot'].forEach(function (key) {
    if (!rows[key]) lines.push('- **' + key + '** — not measured in this run.');
  });

  // The password-protected registry measures genuinely different things
  // (a login, not a digest), so it is not squeezed into the same columns.
  var a = rows.auth;
  lines.push('');
  if (a) {
    lines.push('**' + (a.registry || 'password-protected registry') + '**');
    lines.push('');
    lines.push('- Sign-in challenge: ' + wordChallenge(a.challenge));
    lines.push('- Refused as a credentials problem: ' + (a.auth || 'not measured in this run'));
    lines.push('- Remembered per host: ' + (a.remembered || 'not measured in this run'));
    lines.push('- Never reported as up to date: ' + (a.never_ok || 'not measured in this run'));
  } else {
    lines.push('- **auth** — not measured in this run.');
  }
  lines.push('');
  return lines;
}

// Section 4: one paragraph per fact, each keyed off a value present in the
// dump rather than typed in. Skips a fact entirely when nothing in this
// run triggers it, so an empty dump produces an empty (not wrong) section.
function buildFacts(publicRows, selfhostedRows) {
  var lines = ['## What the numbers mean', ''];
  var n = publicRows.length;

  // A registry that was never reached measured nothing, so it belongs in
  // neither camp — counting an unknown as a "no" would state a fact this run
  // did not establish, which is the stale-note problem wearing a third coat.
  var measured304 = publicRows.filter(function (r) {
    return r['304'] === 'yes' || r['304'] === 'no (200)' || r['304'] === 'no etag sent';
  });
  var noConditional = measured304.filter(function (r) { return r['304'] !== 'yes'; });
  if (noConditional.length > 0) {
    lines.push('- ' + noConditional.length + ' of the ' + measured304.length + ' registries this run ' +
      'reached (' + joinList(noConditional.map(function (r) { return r.registry; })) +
      ') do not honour the cheap conditional re-ask PLAN_90 relies on — asking "has this changed?" ' +
      'saves nothing at those registries, and a full digest fetch is paid every pass regardless.');
  }
  var unmeasured = publicRows.filter(function (r) { return measured304.indexOf(r) === -1; });
  if (unmeasured.length > 0) {
    lines.push('- ' + joinList(unmeasured.map(function (r) { return r.registry; })) +
      ' answered nothing this run, so nothing above is claimed about ' +
      (unmeasured.length === 1 ? 'it' : 'them') + ' — the gap is the finding.');
  }

  var noAllowance = publicRows.filter(function (r) { return r.ratelimit === 'not sent'; });
  if (noAllowance.length > 0) {
    lines.push('- ' + noAllowance.length + ' of ' + n + ' registries (' +
      joinList(noAllowance.map(function (r) { return r.registry; })) +
      ') send no allowance headers at all, so a future wallet feature has to keep its own tally ' +
      'for them rather than reading one back from the registry.');
  }

  var noAuth = publicRows.filter(function (r) { return r.challenge === 'none'; });
  if (noAuth.length > 0) {
    lines.push('- ' + joinList(noAuth.map(function (r) { return r.registry; })) +
      ' need' + (noAuth.length === 1 ? 's' : '') + ' no token at all — the open-registry branch’s ' +
      'only live case among the nine.');
  }

  var computed = publicRows.filter(function (r) { return r.digest_from === 'computed (no header)'; });
  if (computed.length > 0) {
    lines.push('- ' + joinList(computed.map(function (r) { return r.registry; })) +
      ' names no digest in its reply, which is why the computed-from-the-bytes fallback exists at all: ' +
      'without it those registries would report no digest, not a wrong one.');
  }

  // The exception to "key off a column": the realm host is not itself a
  // column the suite records, only the registry name is — so this one fact
  // is keyed off which registry appears, not off an observed value.
  var gitlab = publicRows.some(function (r) { return r.registry === 'registry.gitlab.com'; });
  if (gitlab) {
    lines.push('- registry.gitlab.com names its token realm on a different host entirely — proof ' +
      'the realm the challenge names has to be followed wherever it points, rather than assumed to ' +
      'sit on the registry’s own host.');
  }

  lines.push('');
  return lines;
}

function buildGuards(publicRows, selfhostedRows) {
  var lines = ['## Where a quirk needed code', ''];
  var byName = {};
  publicRows.forEach(function (r) { byName[r.registry] = true; });

  if (byName['ghcr.io'] || byName['codeberg.org']) {
    var who = ['ghcr.io', 'codeberg.org'].filter(function (h) { return byName[h]; });
    lines.push('- **The placeholder-scope fix in `staxx_registry_token()`** — ' + joinList(who) +
      ' answer `/v2/` with a placeholder repository scope in the challenge itself; trusting it ' +
      'instead of building the scope from the repository actually being asked about breaks every ' +
      'image on the affected host. Proven again by this run.');
  }

  var anyComputed = publicRows.some(function (r) { return r.digest_from === 'computed (no header)'; });
  if (anyComputed) {
    lines.push('- **The computed-digest fallback in `staxx_registry_digest()`** — a registry that ' +
      'names no digest header gets one computed from the exact bytes served, rather than being ' +
      'reported as having no digest at all.');
  }

  selfhostedRows = selfhostedRows || {};
  if (selfhostedRows.open || selfhostedRows.zot) {
    lines.push('- **The plain-HTTP transport opt-in in `staxx_registry_trusted()` / ' +
      '`staxx_registry_challenge()`** — a self-hosted registry with no certificate is only reachable ' +
      'at all once its host is named in `REGISTRY_TRUST`; the hostile-redirect guard on the ' +
      'challenge’s realm is unchanged either way.');
  }

  lines.push('');
  return lines;
}

// Assembles the full note as a string. Pure — no filesystem access — so the
// self-test can call it directly without writing anything real.
function buildNote(quirks, selfhosted) {
  var publicRows = Array.isArray(quirks.rows) ? quirks.rows : [];
  var lines = [];
  lines = lines.concat(buildHeader(quirks, selfhosted));
  lines = lines.concat(buildPublicTable(publicRows));
  lines = lines.concat(buildSelfhostedTable(selfhosted.rows));
  lines = lines.concat(buildFacts(publicRows, selfhosted.rows || {}));
  lines = lines.concat(buildGuards(publicRows, selfhosted.rows || {}));
  return lines.join('\n');
}

/* ---- normal (generate) mode ------------------------------------------------ */

function generate(quirksPath, selfhostedPath, outPath) {
  var q = loadDump(quirksPath, 'registry_quirks.php');
  if (!q.ok) { console.error(q.error); process.exit(1); }
  var s = loadDump(selfhostedPath, 'registry_selfhosted.php');
  if (!s.ok) { console.error(s.error); process.exit(1); }

  var qc = checkClean(q.data, 'registry_quirks.php');
  if (!qc.ok) { console.error(qc.error); process.exit(1); }
  var sc = checkClean(s.data, 'registry_selfhosted.php');
  if (!sc.ok) { console.error(sc.error); process.exit(1); }

  var note = buildNote(q.data, s.data);
  fs.writeFileSync(outPath, note + '\n', 'utf8');
  console.log('wrote ' + outPath);
}

/* ---- self-test mode -------------------------------------------------------- */

function runSelfTest() {
  var pass = 0, fail = 0;
  function ok(name, condition, detail) {
    if (condition) { pass++; console.log('  ok    ' + name); return true; }
    fail++;
    console.log('  FAIL  ' + name + (detail ? '\n          ' + String(detail).replace(/\n/g, '\n          ') : ''));
    return false;
  }

  var FIX = path.join(ROOT, 'tests', 'fixtures', 'registry-dumps');
  function load(name) { return JSON.parse(fs.readFileSync(path.join(FIX, name), 'utf8')); }

  console.log('\n1. Every registry in the dump appears, none silently dropped');
  (function () {
    var q = load('quirks-ok.json'), s = load('selfhosted-ok.json');
    var note = buildNote(q, s);
    q.rows.forEach(function (r) {
      ok('public row "' + r.registry + '" appears in the note', note.indexOf(r.registry) !== -1);
    });
    ['open registry:2', 'zot', 'auth registry:2'].forEach(function (name) {
      ok('self-hosted row "' + name + '" appears in the note', note.indexOf(name) !== -1);
    });
  })();

  console.log('\n2. Cell-by-cell check on one full public row');
  (function () {
    var q = load('quirks-ok.json'), s = load('selfhosted-ok.json');
    var note = buildNote(q, s);
    // public.ecr.aws exercises every non-trivial rendering: bearer, yes,
    // "no etag sent", "not sent", yes, "computed (no header)".
    var expected = row(['public.ecr.aws', 'bearer token', 'yes', 'no — no entity tag sent',
                         'no', 'yes', 'computed from the bytes served']);
    ok('the public.ecr.aws row lands in the right columns, not shifted by one',
       note.indexOf(expected) !== -1, 'expected line:\n' + expected + '\n\nnote was:\n' + note);
  })();

  console.log('\n3. Keyed prose fires on the value it claims to, not on everything');
  (function () {
    var q = load('quirks-ok.json'), s = load('selfhosted-ok.json');
    var note = buildNote(q, s);
    // docker.io honours the conditional re-ask (304: yes) — must not be
    // named in the "do not honour" sentence.
    var noConditionalPara = note.split('\n').filter(function (l) {
      return l.indexOf('do not honour the cheap conditional re-ask') !== -1;
    })[0] || '';
    ok('a registry that answers 304 is not named in the "saves nothing here" note',
       noConditionalPara.indexOf('docker.io') === -1, noConditionalPara);
    ok('a registry that answers 200 instead of 304 is named in the "saves nothing here" note',
       noConditionalPara.indexOf('ghcr.io') !== -1, noConditionalPara);
    ok('the open-registry sentence names mcr.microsoft.com, the only "none" challenge',
       note.indexOf('mcr.microsoft.com need') !== -1 &&
       note.indexOf('docker.io need') === -1, note);
  })();

  console.log('\n4. A dump reporting failures is refused, naming the suite and the count');
  (function () {
    var bad = load('quirks-fails.json');
    var r = checkClean(bad, 'registry_quirks.php');
    ok('checkClean reports not-ok', r.ok === false);
    ok('the refusal names the suite', r.error.indexOf('registry_quirks.php') !== -1, r.error);
    ok('the refusal names the failing count', r.error.indexOf('2') !== -1, r.error);
  })();

  console.log('\n5. A skipped or partial run shows as a gap rather than vanishing');
  (function () {
    var q = load('quirks-ok.json'), sPartial = load('selfhosted-partial.json');
    var note = buildNote(q, sPartial);
    ok('quay.io (unreachable, skip) still appears as a row rather than being dropped',
       note.indexOf('quay.io') !== -1);
    ok('quay.io’s skipped digest check reads as "skipped", not silently blank',
       note.indexOf(row(['quay.io', 'unreachable', 'unknown', 'unknown', 'unknown', 'skipped', 'unknown'])) !== -1,
       note);
    ok('a self-hosted dump missing the zot row states the gap plainly',
       note.indexOf('**zot** — not measured in this run.') !== -1, note);
    ok('a self-hosted dump missing the auth row states the gap plainly',
       note.indexOf('**auth** — not measured in this run.') !== -1, note);
  })();

  console.log('\n' + pass + ' passed, ' + fail + ' failed');
  if (fail > 0) process.exit(1);
}

/* ---- entry point ------------------------------------------------------------ */

function main() {
  var argv = process.argv.slice(2);
  if (argv.indexOf('--selftest') !== -1) { runSelfTest(); return; }

  var outIdx = argv.indexOf('--out');
  var outPath = DEFAULT_OUT;
  if (outIdx !== -1) {
    outPath = argv[outIdx + 1];
    argv.splice(outIdx, 2);
  }
  if (argv.length < 2) {
    console.error('usage: node tests/registry_note.js <quirks.json> <selfhosted.json> [--out <path>]');
    console.error('       node tests/registry_note.js --selftest');
    process.exit(1);
  }
  generate(argv[0], argv[1], outPath);
}

main();
